@host = http://localhost:3000

### Test connection
GET {{host}}/
Content-Type: application/json

### verify token
GET {{host}}/api/orders
Content-Type: application/json
Authorization: b eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODNkODExNjJlOGMwNmIwNTA3YzM1ODQiLCJ1c2VyIjp7Imdvb2dsZUlkIjoiMTA1NTc5NTg3MDY2NDIyMTQ5OTQwIiwiZW1haWwiOiJjaGF1aGFuY2hldGFuMTI3ODlAZ21haWwuY29tIiwibmFtZSI6IkNoZXRhbiBDaGF1aGFuIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0tKR3JyT205Tzh1SjBFSGZ2VHg4bk1CMW5zb29qTEFoaUFBWjJ6R0RyQk5NSUs5dz1zOTYtYyIsIl9pZCI6IjY4M2Q4MTE2MmU4YzA2YjA1MDdjMzU4NCIsIl9fdiI6MH0sImlhdCI6MTc0ODg2MTIwNiwiZXhwIjoxNzQ4ODY0ODA2fQ.GYnS4qdXNXf60w0ntX7gtzgB1VBh7aakr8YxIu5CWic

### creating an order
POST {{host}}/api/orders
Content-Type: application/json

{
  "customerId": "683bea2ad066c737f0549c93",
  "amount": 45.00
}
