@host = http://localhost:3000

### Test connection
GET {{host}}/
Content-Type: application/json

### creating a customer
POST {{host}}/api/customers/
Content-Type: application/json

{
  "name": "chetan",
  "email": "chetan.brown@example.com",
  "visits": 3
}
